set_property PACKAGE_PIN L1 [get_ports {q5[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[3]}]
set_property PACKAGE_PIN P1 [get_ports {q5[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[2]}]
set_property PACKAGE_PIN N3 [get_ports {q5[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[1]}]
set_property PACKAGE_PIN P3 [get_ports {q5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q5[0]}]
set_property PACKAGE_PIN U3 [get_ports {q6[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[3]}]
set_property PACKAGE_PIN W3 [get_ports {q6[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[2]}]
set_property PACKAGE_PIN V3 [get_ports {q6[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[1]}]
set_property PACKAGE_PIN V13 [get_ports {q6[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q6[0]}]
set_property PACKAGE_PIN V14 [get_ports {q7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[3]}]
set_property PACKAGE_PIN U14 [get_ports {q7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[2]}]
set_property PACKAGE_PIN U15 [get_ports {q7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[1]}]
set_property PACKAGE_PIN W18 [get_ports {q7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q7[0]}]
set_property PACKAGE_PIN V19 [get_ports {q8[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q8[3]}]
set_property PACKAGE_PIN U19 [get_ports {q8[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q8[2]}]
set_property PACKAGE_PIN E19 [get_ports {q8[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q8[1]}]
set_property PACKAGE_PIN U16 [get_ports {q8[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q8[0]}]

set_property PACKAGE_PIN U18 [get_ports {switch_middle}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_middle}]
set_property PACKAGE_PIN W19 [get_ports {switch_left}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch_left}]
set_property PACKAGE_PIN T17 [get_ports {switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch}]

# Clock
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

# active low reset
set_property PACKAGE_PIN V17 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]

#8 common segment controls
set_property PACKAGE_PIN W7 [get_ports {segs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[7]}]
set_property PACKAGE_PIN W6 [get_ports {segs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[6]}]
set_property PACKAGE_PIN U8 [get_ports {segs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[5]}]
set_property PACKAGE_PIN V8 [get_ports {segs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[4]}]
set_property PACKAGE_PIN U5 [get_ports {segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
set_property PACKAGE_PIN V5 [get_ports {segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
set_property PACKAGE_PIN U7 [get_ports {segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
set_property PACKAGE_PIN V7 [get_ports {segs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]

set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]