set_property SRC_FILE_INFO {cfile:C:/Users/Alvin/Documents/LogicDesignLabMonday/lab3_2_105033110_ver1/lab3_2_105033110_ver1.srcs/constrs_1/new/freqdiv1Hz.xdc rfile:../../../lab3_2_105033110_ver1.srcs/constrs_1/new/freqdiv1Hz.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports clk_out]
