set_property SRC_FILE_INFO {cfile:C:/Users/Alvin/Documents/LogicDesignLabMonday/lab3_1_105033110_ver1/lab3_1_105033110_ver1.srcs/constrs_1/new/freqdiv27.xdc rfile:../../../lab3_1_105033110_ver1.srcs/constrs_1/new/freqdiv27.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports clk_out]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
